### ISSUE TITLE
Free miners can't use exosuit fabricator.

### ISSUE THREAD

**Issue by Majkl-J** [yogstation13/Yogstation#15322]
### Severity

Inconvenience

### Short Description

Due to the new exosuit fabricator update, free miners were unintentionally removed from the ability to build borgs and exosuits.

### Reproduction

1. Be free miner
2. Build exo fabricator
3. Click on it
4. Invalid credentials

### Round ID

42341

**Comment by TheRyeGuyWhoWillNowDie** [comment]
Solved by #15324

**Comment by wonderinghost** [comment]
> 

this is still broken, none other than that of robotics can access these
