### ISSUE TITLE
Ghost form selection not available to BYOND donor

### ISSUE THREAD

**Issue by CrazyDrakkon** [yogstation13/Yogstation#17625]
### Severity

Low

### Short Description

Ghost form selection preference is unselectable/grayed out (showing my previous selection) as a BYOND donor, stuck as default ghost sprite.

### Reproduction

1. BYOND donor, but not server donor.
2. Attempt to change ghost form in preferences.
3. Persistent between rounds and relogs. 

### Round ID

Round #45057

### Test Merges

#17381

### BYOND Username

Crazy_Drakkon

### Was this done on a locally hosted or non-Yogstation hosted server?

No

**Comment by Xantam-13** [comment]
Hi Drakkon

This is now a Yog-Donor feature and isn't offered by BYOND under their donation perks, it was just something we gave to BYOND donors previously but has been pulled back to Yog-only donors.

**Comment by ThatLing** [comment]
Should be fixed whenever the testmerge is updated

**Comment by ThatLing** [comment]
@CrazyDrakkon Can you check now?

**Comment by CrazyDrakkon** [comment]
@ThatLing Hello I am bad at replying and also still can't choose it. It's no longer grayed out but when I select it it's still default ghost (and orbit path shape)
