### ISSUE TITLE
Cilent chat starts in Darkmode

### ISSUE THREAD

**Issue by 00aquir** [yogstation13/Yogstation#5136]
- it does it every time.
-  just because it was activated once.

**Comment by Altoids1** [comment]
No it doesn't.

If it is, try clearing your BYOND cache.

**Comment by 00aquir** [comment]
I'll see about that but it does because I have to set it back every single time.

**Comment by 00aquir** [comment]
Wow. Confirmedly entirely true. Because I had time, I deleted cache and its folder, uninstalled byond, downloaded new version, downloaded the files and it started in dark mode again, like every time before, and the chat continues to open in dark mode every time I set it back.
The problem is on the other side.

**Comment by 00aquir** [comment]
With that, in the window, the game area now re-shrinks every time I connect (Seemingly only the vertical separator line moves back to the initial position). The "Fit viewport" was and is always on "manual". I mean what the hell? It doesn't save the window settings anymore?

**Comment by 00aquir** [comment]
Now is the first time when it didn't start in darkmode, and the "Sending resources.." sitting in chat, maybe I haven't seen it all this time.

**Comment by Altoids1** [comment]
Fixed by https://github.com/yogstation13/Yogstation-TG/pull/5261, closing.

**Comment by 00aquir** [comment]
"in the window, the game area now re-shrinks every time I connect"

2 years later, this problem still exists..
